# Puerto del Gateway
server.port=8080
# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
# 0. Usuario
spring.cloud.gateway.server.webflux.routes[0].id=usuario-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://usuario-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/usuarios/**

# 1. Carrito
spring.cloud.gateway.server.webflux.routes[1].id=carrito-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://carrito-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/carrito/**

# 2. Inventario
spring.cloud.gateway.server.webflux.routes[2].id=inventario-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventario-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/inventario/**

# 3. Pagos
spring.cloud.gateway.server.webflux.routes[3].id=pagos-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://pagos-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/pagos/**

# 4. Facturaciones
spring.cloud.gateway.server.webflux.routes[4].id=facturaciones-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://facturaciones-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/facturas/**

# 5. Transporte
spring.cloud.gateway.server.webflux.routes[5].id=transporte-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://transporte-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/transporte/**

# 6. Descuentos
spring.cloud.gateway.server.webflux.routes[6].id=descuentos-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://descuentos-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/descuentos/**

# 7. Notificaciones
spring.cloud.gateway.server.webflux.routes[7].id=notificaciones-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://notificaciones-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/notificaciones/**

server.address=0.0.0.0