# 1. Borramos el server.port de aquí para que el local (9000) sea el que mande
# 2. Mantenemos el nombre de la app para que Eureka lo identifique
spring.application.name=api-gateway

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Rutas de Gateway (Ordenadas y sin errores)
spring.cloud.gateway.routes[0].id=usuario-service
spring.cloud.gateway.routes[0].uri=lb://usuario-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/usuario/**

spring.cloud.gateway.routes[1].id=carrito-service
spring.cloud.gateway.routes[1].uri=lb://carrito-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/carritos/**

spring.cloud.gateway.routes[2].id=inventario-service
spring.cloud.gateway.routes[2].uri=lb://inventario-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/inventario/**

spring.cloud.gateway.routes[3].id=pagos-service
spring.cloud.gateway.routes[3].uri=lb://pagos-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/pagos/**

spring.cloud.gateway.routes[4].id=facturaciones-service
spring.cloud.gateway.routes[4].uri=lb://facturaciones-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/facturas/**

spring.cloud.gateway.routes[5].id=transporte-service
spring.cloud.gateway.routes[5].uri=lb://transporte-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/transportes/**

spring.cloud.gateway.routes[6].id=producto-service
spring.cloud.gateway.routes[6].uri=lb://producto-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/productos/**

spring.cloud.gateway.routes[7].id=notificaciones-service
spring.cloud.gateway.routes[7].uri=lb://notificaciones-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/notificaciones/**