server.port=0
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true

# CONFIGURACION DE credenciales de MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/bd_producto
spring.datasource.username=root
spring.datasource.password=
# CONFIGURACION DE SPRING CON MYSQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.address=0.0.0.0

# producto-service/src/main/resources/application.properties
spring.application.name=producto-service
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration